import java.io.BufferedReader;
import java.io.InputStreamReader;
import java.nio.charset.StandardCharsets;
import java.util.regex.Matcher;
import java.util.regex.Pattern;

public class TestJavaParser {
    public static void main(String[] args) throws Exception {
        String input = readAllStdin();

        String startUrl = extractString(input, "startUrl", "unknown-start-url");
        int maxCars = extractInt(input, "maxCars", 1);
        int streamBatchSize = extractInt(input, "streamBatchSize", 1);

        long now = System.currentTimeMillis();

        String item = "{" +
                "\"source\":\"TestJavaParser\"," +
                "\"url\":\"java-test://parser/" + now + "\"," +
                "\"brand\":\"Toyota\"," +
                "\"model\":\"Java Test Car\"," +
                "\"price\":" + (1000000 + maxCars) + "," +
                "\"year\":2026," +
                "\"sale_region\":\"Java Test Region\"," +
                "\"mileage\":" + (streamBatchSize * 1000) + "," +
                "\"transmission\":\"automatic\"," +
                "\"drive_type\":\"awd\"," +
                "\"color\":\"white\"," +
                "\"body_type\":\"wagon\"," +
                "\"steering_wheel\":\"left\"," +
                "\"engine_power\":150," +
                "\"engine_volume\":2.0," +
                "\"fuel_type\":\"gasoline\"," +
                "\"description\":\"Generated by TestJavaParser. startUrl=" + escape(startUrl) + "\"" +
                "}";

        // Parser contract: stdout contains JSON Lines. One line is one batch.
        System.out.println("[" + item + "]");
        System.err.println("TestJavaParser emitted one test record.");
    }

    private static String readAllStdin() throws Exception {
        BufferedReader reader = new BufferedReader(new InputStreamReader(System.in, StandardCharsets.UTF_8));
        StringBuilder sb = new StringBuilder();
        String line;
        while ((line = reader.readLine()) != null) {
            sb.append(line).append('\n');
        }
        return sb.toString();
    }

    private static String extractString(String json, String key, String fallback) {
        Pattern pattern = Pattern.compile("\\\"" + Pattern.quote(key) + "\\\"\\s*:\\s*\\\"(.*?)\\\"");
        Matcher matcher = pattern.matcher(json);
        if (matcher.find()) {
            return matcher.group(1).replace("\\\"", "\"");
        }
        return fallback;
    }

    private static int extractInt(String json, String key, int fallback) {
        Pattern pattern = Pattern.compile("\\\"" + Pattern.quote(key) + "\\\"\\s*:\\s*(\\d+)");
        Matcher matcher = pattern.matcher(json);
        if (matcher.find()) {
            try {
                return Integer.parseInt(matcher.group(1));
            } catch (Exception ignored) {
                return fallback;
            }
        }
        return fallback;
    }

    private static String escape(String value) {
        if (value == null) return "";
        return value
                .replace("\\", "\\\\")
                .replace("\"", "\\\"")
                .replace("\r", " ")
                .replace("\n", " ");
    }
}
